const TYPES = {
  GET_TABLE_DATA_ORDER: "GET_TABLE_DATA_ORDER",
  GET_CARS: "GET_CARS",
  POST_LOGIN: "POST_LOGIN",
  GET_CAR: "GET_CAR",
  FETCH_DATA: "FETCH_DATA",
  GET_CHART_DATA_ORDER: "GET_CHART_DATA_ORDER",
  SEARCH_QUERY: "SEARCH_QUERY",
}

export default TYPES
